const searchResult = 
`<li><a href="#">IIT Kharagpur</a></li>
<li><a href="#">IIT Bombay</a></li>
<li><a href="#">IIT Kanpur</a></li>
<li><a href="#">IIT Madras</a></li>
<li><a href="#">IIT Delhi</a></li>
<li><a href="#">IIT Guwahati</a></li>
<li><a href="#">IIT Roorkee</a></li>
<li><a href="#">IIT Bhubaneswar</a></li>
<li><a href="#">IIT Gandhinagar</a></li>
<li><a href="#">IIT Hyderabad</a></li>
<li><a href="#">IIT Jodhpur</a></li>
<li><a href="#">IIT Patna</a></li>
<li><a href="#">IIT Ropar</a></li>
<li><a href="#">IIT Indore</a></li>
<li><a href="#">IIT Mandi</a></li>
<li><a href="#">IIT (BHU) Varanasi (formerly known as IIT Varanasi or IIT BHU)</a></li>
<li><a href="#">IIT Palakkad</a></li>
<li><a href="#">IIT Tirupati</a></li>
<li><a href="#">IIT Dhanbad (formerly known as ISM Dhanbad or IIT(ISM) Dhanbad)</a></li>
<li><a href="#">IIT Bhilai</a></li>
<li><a href="#">IIT Goa</a></li>
<li><a href="#">IIT Jammu</a></li>
<li><a href="#">IIT Dharwad</a></li>
<li><a href="#">NIT Warangal, Telangana</a></li>
        <li><a href="#">NIT Tiruchirappalli, Tamil Nadu</a></li>
        <li><a href="#">NIT Surathkal, Karnataka</a></li>
        <li><a href="#">NIT Calicut, Kerala</a></li>
        <li><a href="#">NIT Rourkela, Odisha</a></li>
        <li><a href="#">NIT Kurukshetra, Haryana</a></li>
        <li><a href="#">NIT Durgapur, West Bengal</a></li>
        <li><a href="#">NIT Hamirpur, Himachal Pradesh</a></li>
        <li><a href="#">NIT Jalandhar, Punjab</a></li>
        <li><a href="#">NIT Agartala, Tripura</a></li>
        <li><a href="#">NIT Patna, Bihar</a></li>
        <li><a href="#">NIT Raipur, Chhattisgarh</a></li>
        <li><a href="#">NIT Silchar, Assam</a></li>
        <li><a href="#">NIT Srinagar, Jammu and Kashmir</a></li>
        <li><a href="#">NIT Surat, Gujarat</a></li>
        <li><a href="#">NIT Nagpur, Maharashtra</a></li>
        <li><a href="#">NIT Jamshedpur, Jharkhand</a></li>
        <li><a href="#">NIT Allahabad, Uttar Pradesh</a></li>
        <li><a href="#">NIT Bhopal, Madhya Pradesh</a></li>
        <li><a href="#">NIT Delhi</a></li>
        <li><a href="#">NIT Puducherry</a></li>
        <li><a href="#">NIT Goa</a></li>
        <li><a href="#">NIT Manipur</a></li>
        <li><a href="#">NIT Meghalaya</a></li>
        <li><a href="#">NIT Mizoram</a></li>
        <li><a href="#">NIT Nagaland</a></li>
        <li><a href="#">NIT Sikkim</a></li>
        <li><a href="#">NIT Arunachal Pradesh</a></li>
        <li><a href="#">NIT Uttarakhand</a></li>
        <li><a href="#">NIT Andhra Pradesh</a></li>
        <li><a href="#">NIT Jammu and Kashmir (Temporary Campus)</a></li>
        <li><a href="#">IIIT Hyderabad, Telangana</a></li>
        <li><a href="#">IIIT Bangalore, Karnataka</a></li>
        <li><a href="#">IIIT Delhi</a></li>
        <li><a href="#">IIIT Allahabad, Uttar Pradesh</a></li>
        <li><a href="#">IIIT Bhubaneswar, Odisha</a></li>
        <li><a href="#">IIIT Pune, Maharashtra</a></li>
        <li><a href="#">IIIT Gwalior, Madhya Pradesh</a></li>
        <li><a href="#">IIIT Kalyani, West Bengal</a></li>
        <li><a href="#">IIIT Kottayam, Kerala</a></li>
        <li><a href="#">IIIT Kota, Rajasthan</a></li>
        <li><a href="#">IIIT Lucknow, Uttar Pradesh</a></li>
        <li><a href="#">IIIT Manipur</a></li>
        <li><a href="#">IIIT Nagpur, Maharashtra</a></li>
        <li><a href="#">IIIT Ranchi, Jharkhand</a></li>
        <li><a href="#">IIIT Sonepat, Haryana</a></li>
        <li><a href="#">IIIT Sri City, Andhra Pradesh</a></li>
        <li><a href="#">IIIT Surat, Gujarat</a></li>
        <li><a href="#">IIIT Una, Himachal Pradesh</a></li>
        <li><a href="#">IIIT Vadodara, Gujarat</a></li>
        <li><a href="#">IIIT Bhagalpur, Bihar</a></li>
        <li><a href="#">IIIT Agartala, Tripura</a></li>
        <li><a href="#">AIIMS New Delhi, Delhi</a></li>
        <li><a href="#">AIIMS Bhopal, Madhya Pradesh</a></li>
        <li><a href="#">AIIMS Bhubaneswar, Odisha</a></li>
        <li><a href="#">AIIMS Jodhpur, Rajasthan</a></li>
        <li><a href="#">AIIMS Patna, Bihar</a></li>
        <li><a href="#">AIIMS Raipur, Chhattisgarh</a></li>
        <li><a href="#">AIIMS Rishikesh, Uttarakhand</a></li>
        <li><a href="#">AIIMS Bathinda, Punjab</a></li>
        <li><a href="#">AIIMS Gorakhpur, Uttar Pradesh</a></li>
        <li><a href="#">AIIMS Nagpur, Maharashtra</a></li>
        <li><a href="#">AIIMS Rae Bareli, Uttar Pradesh</a></li>
        <li><a href="#">AIIMS Bibinagar, Telangana</a></li>
        <li><a href="#">IIM Ahmedabad, Gujarat</a></li>
        <li><a href="#">IIM Bangalore, Karnataka</a></li>
        <li><a href="#">IIM Calcutta, West Bengal</a></li>
        <li><a href="#">IIM Lucknow, Uttar Pradesh</a></li>
        <li><a href="#">IIM Kozhikode, Kerala</a></li>
        <li><a href="#">IIM Indore, Madhya Pradesh</a></li>
        <li><a href="#">IIM Shillong, Meghalaya</a></li>
        <li><a href="#">IIM Ranchi, Jharkhand</a></li>
        <li><a href="#">IIM Raipur, Chhattisgarh</a></li>
        <li><a href="#">IIM Rohtak, Haryana</a></li>
        <li><a href="#">IIM Trichy (Tiruchirappalli), Tamil Nadu</a></li>
        <li><a href="#">IIM Udaipur, Rajasthan</a></li>
        <li><a href="#">IIM Kashipur, Uttarakhand</a></li>
        <li><a href="#">IIM Nagpur, Maharashtra</a></li>
        <li><a href="#">IIM Visakhapatnam, Andhra Pradesh</a></li>
        <li><a href="#">IIM Bodh Gaya, Bihar</a></li>
        <li><a href="#">IIM Sirmaur, Himachal Pradesh</a></li>
        <li><a href="#">IIM Sambalpur, Odisha</a></li>
        <li><a href="#">IIM Amritsar, Punjab</a></li>
        <li><a href="#">IIM Jammu, Jammu and Kashmir</a></li>`;

document.getElementById('myUL').innerHTML = searchResult;